api/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from .views.category import CategoryList, CategoryDetail

app_name = "api"
urlpatterns = [
    path("categories/", CategoryList.as_view()),
    path("categories/<int:pk>/", CategoryDetail.as_view())
]

urlpatterns = format_suffix_patterns(urlpatterns)

inventory_control/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('fornecedores/', include("suppliers.urls")),
    path('produtos/', include("products.urls")),
    path('', include('users.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('api.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

suppliers/urls.py
from django.urls import path
from . import views
from .views import SupplierListView, SupplierSearchView, SupplierCreateView, SupplierUpdateView, SupplierDeleteView

app_name = "suppliers"
urlpatterns = [
    path("", SupplierListView.as_view(), name="index"),
    path("cadastro", SupplierCreateView.as_view(), name="create"),
    path("<int:pk>/delete", SupplierDeleteView.as_view(), name="delete"), # fornecedores/1/delete
    path("search", SupplierSearchView.as_view(), name="search"),
    path("<int:id>/toggle_enabled", views.toggle_enabled, name="toggle_enabled"),
    path("<slug:slug>", SupplierUpdateView.as_view(), name="update")
]

transactions/models.py
from django.db import models
from products.models import Product
from suppliers.models import Supplier

class Transactions(models.Model):
    TRANSACTION_CHOICES = {
            "E": "Entrada",
            "S": "Saída"
    }

    transaction_type = models.CharField(max_length=1, choices=TRANSACTION_CHOICES)
    product = models.ForeignKey(Product, on_delete=models.DO_NOTHING)
    quantity = models.DecimalField(max_digits=255, decimal_places=2)
    date = models.DateTimeField(auto_now_add=True)
    supplier = models.ForeignKey(Supplier, on_delete=models.DO_NOTHING)

transactions/views.py
from django.shortcuts import render
from .models import Transactions
from django.core.paginator import Paginator

def index(request):
    transactions = Transactions.objects.order_by("-date")

    paginator = Paginator(transactions, 100)
    page_number = paginator.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        "transactions": page_obj
    }

    return render(request, "transactions/index.html", context)

transactions/templates/transactions/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}Transações{% endblock  %}
{% block content %}
    <h2 class="mb-3">Transações</h2>

    {% comment %} <a 
        href="{% url 'transactions:create' %}"
        title="Cadastrar novo fornecedor"
        class="btn btn-primary btn-sticky-bottom">
        <i class="bi bi-plus"></i>
    </a> {% endcomment %}

    {% comment %} Filtro {% endcomment %}
    {% comment %} <form method="get" action="{% url 'suppliers:search' %}" class="row mb-3">
        <div class="col">
            <input value="{{ request.GET.q }}" class="form-control" type="text" name="q" placeholder="Buscar">
        </div>
        <div class="col-auto">
            <button type="submit" class="btn btn-primary">Buscar</button>
        </div>
    </form> {% endcomment %}

    {% comment %} Tabela de fornecedores {% endcomment %}
    <div class="table-responsive">
        <table class="table table-striped table-sm">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Razão Social</th>
                    <th>Nome Fantasia</th>
                    <th>Representante</th>
                    <th>E-mail</th>
                </tr>
            </thead>
            <tbody>
                {% for supplier in suppliers %}
                <tr>
                    <td>{{ supplier.id }}</td>
                    <td>{{ supplier.company_name|title }}</td>
                    <td>{{ supplier.fantasy_name|title }}</td>
                    <td>{{ supplier.representative|title }}</td>
                    <td>{{ supplier.email }}</td>
                    <td>{{ supplier.phone|format_phone}}</td>
                    <td>
                        <input {% if supplier.enabled %}checked{% endif %} data-url="{% url 'suppliers:toggle_enabled' supplier.id %}" type="checkbox" class="form-check-input">
                    </td>
                    <td class="d-flex gap-1">
                        <a href="{% url 'suppliers:update' supplier.slug %}" class="btn btn-warning btn-sm" title="Editar fornecedor">
                            <i class="bi bi-pencil"></i>
                        </a>
                        <form method="post" action="{% url 'suppliers:delete' supplier.id %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger btn-sm" title="Remover fornecedor">
                                <i class="bi bi-trash"></i>
                            </button>
                        </form>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="8" class="text=center">Nenhum fornecedor cadastrado</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% comment %} Paginação {% endcomment %}
        {% if suppliers.paginator.num_pages > 1 %}
        <nav aria-label="Paginação da página">
            <ul class="pagination justify-content-end">
                {% if suppliers.has_previous %}
                <li class="page-item">
                    <a href="?page={{ suppliers.previous_page_number }}" class="page-link" aria-label="Anterior">&laquo;</a>
                </li>
                {% endif %}
                <li class="page-item active">
                    <span class="page-link">{{ suppliers.number }}</span>
                </li>
                {% if suppliers.has_next %}
                <li class="page-item">
                    <a href="?page={{ suppliers.next_page_number }}" class="page-link" aria-label="Próximo">&raquo;</a>
                </li>
                {% endif %}
            </ul>
        </nav>
        {% endif %}
    </div>
{% endblock %}
{% endblock  %}