api/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from .views.category import CategoryList, CategoryDetail

app_name = "api"
urlpatterns = [
    path("categories/", CategoryList.as_view()),
    path("categories/<int:pk>/", CategoryDetail.as_view())
]

urlpatterns = format_suffix_patterns(urlpatterns)

inventory_control/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('fornecedores/', include("suppliers.urls")),
    path('produtos/', include("products.urls")),
    path('', include('users.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('api.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views

app_name = "products"
urlpatterns = [
    path("", views.index, name="index"),
    path("cadastro", views.create, name="create"),
    path("<int:id>/delete", views.delete, name="delete"), # fornecedores/1/delete
    path("search", views.search, name="search"),
    path("<int:id>/toggle_enabled", views.toggle_enabled, name="toggle_enabled"),
    path("<slug:slug>", views.update, name="update"),
    path("categorias/", views.index_category, name="index_category"),
    path("categorias/cadastro", views.create_category, name="create_category"),
    path("categories/<int:id>/delete", views.delete_category, name="delete_category"),
    path("categories/search", views.search_category, name="search_category"),
    path("categorias/<slug:slug>/", views.update_category, name="update_category"),
    path("<int:id>/suppliers/", views.get_suppliers_from_product, name="suppliers"),
    path("<int:id>/delete_supplier", views.delete_supplier_from_product, name="delete_supplier")
]

products/forms.py
from django import forms
from .models import Product, Category, SupplierProduct, ProductInventory
import re
from crispy_forms.helper import FormHelper

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        exclude = ["thumbnail", "slug", "is_perishable"]

        labels = {
            "name": "Nome",
            "description": "Descrição",
            "sale_price": "Preço de venda",
            "expiration_date": "Data de expiração",
            "photo": "Imagem do produto",
            "enabled": "Ativo",
            "category": "Categoria"
        }

        error_messages = {
            "name": {
                "unique": "Já existe um produto cadastrado com esse nome",
                "required": "O campo nome é obrigatório"
            },
            "description": {
                "required": "O campo descrição é obrigatório"
            },
            "sale_price": {
                "required": "O campo preço de venda é obrigatório",
            },
        }

        widgets = {
            "expiration_date": forms.DateInput(attrs={"type":"date"}, format="%Y-%m-%d")
        }

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = "__all__"

        labels = {
            "name": "Nome",
            "description": "Descrição",
        }

        error_messages = {
            "name": {
                "required": "O campo nome é obrigatório",
                "unique": "Já existe uma categoria cadastrada com esse nome"
            },
            "description": {
                "required": "O campo descrição é obrigatório"
            },
        }

class SupplierProductForm(forms.ModelForm):
    class Meta:
        model = SupplierProduct
        exclude = ["product"]
        widgets = {
            "cost_price": forms.NumberInput(attrs={"placeholder": "Preço de custo"})
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_show_labels = False

SupplierProductFormSet = forms.inlineformset_factory(
    Product,
    SupplierProduct,
    form=SupplierProductForm,
    extra=1,
    can_delete=True,
    max_num=5
)

class ProductInventoryForm(forms.ModelForm):
    class Meta:
        model = ProductInventory
        exclude = ["product"]
        widgets = {
            "quantity": forms.NumberInput(attrs={"placeholder": "Quantidade"}),
            "local": forms.TextInput(attrs={"placeholder": "Local"})
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_show_labels = False

ProductInventoryFormSet = forms.inlineformset_factory(
    Product,
    ProductInventory,
    form=ProductInventoryForm,
    extra=1,
    can_delete=False,
    max_num = 1
)

api/views/category.py
from products.models import Category
from rest_framework import mixins, generics
from rest_framework import serializers

class CategorySerializer(serializers.ModelSerializer):
    class Meta:
        model = Category
        exclude = ["slug"]

class CategoryList(mixins.ListModelMixin, mixins.CreateModelMixin, generics.GenericAPIView):
    """
    Lista todas as categorias ou cria uma nova categoria.
    """
    queryset = Category.objects.all()
    serializer_class = CategorySerializer

    def get(self, request, *args, **kwargs):
        return self.list(request, *args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        return self.create(request, *args, **kwargs)
    
class CategoryDetail(mixins.RetrieveModelMixin,
                     mixins.UpdateModelMixin,
                     mixins.DestroyModelMixin,
                     generics.GenericAPIView):
    """Obtém, atualiza ou remove uma categoria"""
    queryset = Category.objects.all()
    serializer_class = CategorySerializer

    def get(self, request, *args, **kwargs):
        return self.retrieve(request, *args, **kwargs)
    
    def put(self, request, *args, **kwargs):
        return self.update(request, *args, **kwargs)
    
    def delete(self, request, *args, **kwargs):
        return self.destroy(request, *args, **kwargs)

products/views.py
from django.db import IntegrityError
from django.shortcuts import render, redirect, get_object_or_404
from .models import Product, Category, SupplierProduct, ProductInventory
from django.core.paginator import Paginator
from django.views.decorators.http import require_POST, require_GET
from django.db.models import Q 
from django.http import JsonResponse
from django.urls import reverse
from .forms import ProductForm, CategoryForm
from django.contrib import messages
from .forms import SupplierProductFormSet, ProductInventoryFormSet

# Create your views here.
def index(request):
    products = Product.objects.order_by("-id")
    product_inventory = ProductInventory.objects.order_by("-id")

    # Aplicando a paginação
    paginator = Paginator(products, 100)
    # /fornecedores?page=1 -> Obtendo a página da URL
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        "products": page_obj,
        "product_inventory": product_inventory
        }
    
    return render(request, "products/index.html", context)

def search(request):
    # Obtendo o valor da requisição (Formulário)
    search_value = request.GET.get("q").strip()

    # Verificando se algo foi digitado
    if not search_value:
        return redirect("products:index")
    
    # Filtrando os produtos
    #  O Q é usado para combinar filtros (& ou |)
    products = Product.objects\
        .filter(Q(name__icontains=search_value) | Q(category__name__icontains=search_value))\
        .order_by("-id")

    paginator = Paginator(products, 100)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = { "products": page_obj}

    return render(request, "products/index.html", context)

def create(request):
    form_action = reverse("products:create")
    # POST
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        
        if form.is_valid():
            product = form.save()
            
            supplier_product_formset = SupplierProductFormSet(request.POST, instance=product)
            product_inventory_formset = ProductInventoryFormSet(request.POST, instance=product)
            
            if not supplier_product_formset.is_valid():                      
                messages.error(request, "Falha ao cadastrar os fornecedores do produto")
                product.delete()
                
                supplier_product_formset = SupplierProductFormSet(request.POST)
                product_inventory_formset = ProductInventoryFormSet(request.POST, instance=product)
        
                context = { 
                    "form": form, 
                    "supplier_product_formset": supplier_product_formset, 
                    "form_action": form_action,
                    "product_inventory_formset": product_inventory_formset}
                
                return render(request, "products/create.html", context)
            
            if product_inventory_formset.is_valid():
                messages.success(request, "O produto foi cadastrado com sucesso!")
                supplier_product_formset.save()
                product_inventory_formset.save()
            else:
                messages.error(request, "Falha ao cadastrar o estoque do produto")
                product.delete()
                supplier_product_formset = SupplierProductFormSet(request.POST)
                product_inventory_formset = ProductInventoryFormSet(request.POST, instance=product)
        
                context = { 
                    "form": form, 
                    "supplier_product_formset": supplier_product_formset, 
                    "form_action": form_action,
                    "product_inventory_formset": product_inventory_formset}
                
                return render(request, "products/create.html", context)
            
            return redirect("products:index")
                
        messages.error(request, "Falha ao cadastrar o produto. Verifique o preenchimento dos campos.")
        
        supplier_product_formset = SupplierProductFormSet(request.POST)
        
        context = { "form": form, "supplier_product_formset": supplier_product_formset, "form_action": form_action }
        
        return render(request, "products/create.html", context)

    # GET
    form = ProductForm()
    supplier_product_formset = SupplierProductFormSet()
    product_inventory_formset = ProductInventoryFormSet()

    context = {
        "form": form, 
        "form_action": form_action,
        "supplier_product_formset": supplier_product_formset,
        "product_inventory_formset": product_inventory_formset
        }

    return render(request, "products/create.html", context)

def update(request, slug):
    product = get_object_or_404(Product, slug=slug)
    form_action = reverse("products:update", args=(slug,))
    supplier_product_formset = SupplierProductFormSet(request.POST, instance=product)

    # POST
    if request.method == "POST":
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            if form.cleaned_data["photo"] is False:
                product.thumbnail.delete()
            form.save()

            try:
                if supplier_product_formset.is_valid():
                    supplier_product_formset.save()
                    messages.success(request, "O produto foi atualizado com sucesso!")
                    return redirect("products:index")
                else:
                    messages.error(request, "Não é possível atualizar o produto. Verifique os campos de fornecedor")
                    
                    supplier_product_formset = SupplierProductFormSet(instance=product)

                    context = {
                    "form": form,
                    "supplier_product_formset": supplier_product_formset,
                    "form_action": form_action
                }

                return render(request, "products/create.html", context)

            except IntegrityError:
                messages.error(request, "Não é possível cadastrar o mesmo fornecedor para o mesmo produto.")

                context = {
                    "form": form,
                    "supplier_product_formset": supplier_product_formset,
                    "form_action": form_action
                }

                return render(request, "products/create.html", context)
        
        context = {
            "form_action": form_action,
            "supplier_product_formset": supplier_product_formset,
            "form": form
        }

        return render(request, "products/create.html", context)
    
    # GET
    form =  ProductForm(instance=product)
    supplier_product_formset = SupplierProductFormSet(instance=product)

    context = {
        "form_action": form_action,
        "form": form,
        "supplier_product_formset": supplier_product_formset
    }

    return render(request, "products/create.html", context)

@require_POST
def delete(request, id):
    product = get_object_or_404(Product, pk=id)
    product.delete()

    return redirect("products:index")

@require_POST
def toggle_enabled(request, id):
    product = get_object_or_404(Product, pk=id)

    product.enabled = not product.enabled
    product.save()
    
    return JsonResponse({ "message": "success" })

def index_category(request):
    categories = Category.objects.order_by("-id")

    paginator = Paginator(categories, 100)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        "categories": page_obj
    }

    return render(request, "categories/index.html", context)

def search_category(request):
    # Obtendo o valor da requisição (Formulário)
    search_value = request.GET.get("q").strip()

    # Verificando se algo foi digitado
    if not search_value:
        return redirect("products:index_category")
    
    # Filtrando os produtos
    #  O Q é usado para combinar filtros (& ou |)
    products = Category.objects\
        .filter(Q(name__icontains=search_value) | Q(category__name__icontains=search_value))\
        .order_by("-id")

    paginator = Paginator(products, 100)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = { "products": page_obj}

    return render(request, "categories/index.html", context)

def create_category(request):
    form_action = reverse("products:create_category")
    
    # POST
    if request.method == "POST":
        form = CategoryForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request, "A categoria foi cadastrada com sucesso!")
            return redirect("products:index")
        
        messages.error(request, "Falha ao cadastrar o produto. Verifique o preenchimento dos campos.")

        context = {
            "form_action": form_action,
            "form": form,
        }

        return render(request, "categories/create.html", context)
    
    form = CategoryForm()

    context = {
        "form_action": form_action,
        "form": form
    }

    return render(request, "categories/create.html", context)

def update_category(request, slug):
    category = get_object_or_404(Category, slug=slug)

    # POST
    if request.method == "POST":
        form = CategoryForm(request.POST, instance=category)
        if form.is_valid():
            form.save()
            messages.success(request, "Categoria atualizada com sucesso!")
            return redirect("products:index_category")
        
        context = {
            "form": form
        }

        return render(request, "category/create.html", context)
    
    # GET
    form =  CategoryForm(instance=category)

    context = {
        "form": form
    }

    return render(request, "categories/create.html", context)

@require_POST
def delete_supplier_from_product(request, id):

products/templates/categories/create.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Cadastro de categorias{% endblock  %}
{% block head %}
    <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.5/dist/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js" integrity="sha512-pHVGpX7F/27yZ0ISY+VVjyULApbDlD0/X0rgGbTqCE7WFW5MezNTWG/dnhtbBuICzsd0WQPgpE4REBLv+UqChw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
{% endblock  %}
{% block content %}
    {% with create_url="/produtos/categorias/cadastro" %}
        <h2 class="mb-3">
            {% if form_action == create_url %}
            Cadastro de categorias
          {% else %}
            Edição de categorias
          {% endif %}</h2>
        <form action="{{ form_action }}" method="POST" novalidate>
            {% csrf_token %}

            <div class="row mb-3">
                <div class="col">
                    {{ form.name|as_crispy_field }}
                </div>
            </div>
            <div class="row mb-3">
                <div class="col">
                    {{ form.description|as_crispy_field }}
                </div>
            <div class="d-grid">
                <button class="btn btn-primary btn-lg">Salvar</button>
            </div>
        </form>
    {% endwith %}
{% endblock  %}

products/templates/categories/index.html
{% extends "base.html" %}
{% load static %}
{% block head %}
{% endblock  %}
{% block title %}Categorias{% endblock  %}
{% block content %}
    <h2 class="mb-3">Categorias</h2>
    
    <a 
    href="{% url 'products:create_category' %}"
    title="Cadastrar nova categoria"
    class="btn btn-primary btn-sticky-bottom">
    <i class="bi bi-plus"></i>
    </a>

    {% comment %} Filtro {% endcomment %}
    <form method="get" action="{% url 'products:search_category' %}" class="row mb-3">
        <div class="col">
            <input value="{{ request.GET.q }}" class="form-control" type="text" name="q" placeholder="Buscar">
        </div>
        <div class="col-auto">
            <button type="submit" class="btn btn-primary">Buscar</button>
        </div>
    </form>

{% comment %} Tabela de produtos {% endcomment %}
    <div class="table-responsive">
        <table class="table table-striped table-sm">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Nome</th>
                    <th>Descrição</th>
                </tr>
            </thead>
            <tbody>
                {% for category in categories %}
                <tr>
                    <td>{{ category.id }}</td>
                    <td>{{ category.name|title|truncatechars:20 }}</td>
                    <td>{{ category.description }}</td>
                    <td class="d-flex gap-1">
                        <a href="{% url 'products:update_category' category.slug %}" class="btn btn-warning btn-sm" title="Editar categoria">
                            <i class="bi bi-pencil"></i>
                        </a>
                        <form method="post" action="{% url 'products:delete_category' category.id %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger btn-sm" title="Remover categoria">
                                <i class="bi bi-trash"></i>
                            </button>
                        </form>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="9" class="text=center">Nenhum produto cadastrado</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% comment %} Paginação {% endcomment %}
        {% if products.paginator.num_pages > 0 %}
        <nav aria-label="Paginação da página">
            <ul class="pagination justify-content-end">
                {% if products.has_previous %}
                <li class="page-item">
                    <a href="?page={{ products.previous_page_number }}" class="page-link" aria-label="Anterior">&laquo;</a>
                </li>
                {% endif %}
                <li class="page-item active">
                    <span class="page-link">{{ products.number }}</span>
                </li>
                {% if products.has_next %}
                <li class="page-item">
                    <a href="?page={{ products.next_page_number }}" class="page-link" aria-label="Próximo">&raquo;</a>
                </li>
                {% endif %}
            </ul>
        </nav>
        {% endif %}
    </div>

{% endblock  %}