api/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from .views.category import CategoryList, CategoryDetail

app_name = "api"
urlpatterns = [
    path("categories/", CategoryList.as_view()),
    path("categories/<int:pk>/", CategoryDetail.as_view())
]

urlpatterns = format_suffix_patterns(urlpatterns)

inventory_control/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('fornecedores/', include("suppliers.urls")),
    path('produtos/', include("products.urls")),
    path('', include('users.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('api.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views

app_name = "products"
urlpatterns = [
    path("", views.index, name="index"),
    path("cadastro", views.create, name="create"),
    path("<int:id>/delete", views.delete, name="delete"), # fornecedores/1/delete
    path("search", views.search, name="search"),
    path("<int:id>/toggle_enabled", views.toggle_enabled, name="toggle_enabled"),
    path("<slug:slug>", views.update, name="update"),
    path("categorias/", views.index_category, name="index_category"),
    path("categorias/cadastro", views.create_category, name="create_category"),
    path("categories/<int:id>/delete", views.delete_category, name="delete_category"),
    path("categories/search", views.search_category, name="search_category"),
    path("categorias/<slug:slug>/", views.update_category, name="update_category"),
    path("<int:id>/suppliers/", views.get_suppliers_from_product, name="suppliers"),
    path("<int:id>/delete_supplier", views.delete_supplier_from_product, name="delete_supplier")
]

suppliers/urls.py
from django.urls import path
from . import views
from .views import SupplierListView, SupplierSearchView, SupplierCreateView, SupplierUpdateView, SupplierDeleteView

app_name = "suppliers"
urlpatterns = [
    path("", SupplierListView.as_view(), name="index"),
    path("cadastro", SupplierCreateView.as_view(), name="create"),
    path("<int:pk>/delete", SupplierDeleteView.as_view(), name="delete"), # fornecedores/1/delete
    path("search", SupplierSearchView.as_view(), name="search"),
    path("<int:id>/toggle_enabled", views.toggle_enabled, name="toggle_enabled"),
    path("<slug:slug>", SupplierUpdateView.as_view(), name="update")
]

users/urls.py
from django.urls import path
from django.views.generic import RedirectView
from . import views
from .views import UserLoginView, UserLogoutView

app_name = "users"
urlpatterns = [
    path("", RedirectView.as_view(url="/login/", permanent=True)),
    path("usuarios/", views.index, name="index"),
    path("usuarios/cadastro/", views.create, name="create"),
    path("login/", views.UserLoginView.as_view(), name="login"),
    path("usuarios/<str:username>/", views.update, name="update"),
    path("usuarios/<int:id>/delete", views.delete, name="delete"),
    path("logout/", views.UserLogoutView.as_view(), name="logout")
]

base/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        iStock - {% block title %}{% endblock  %}
    </title>
    <link rel="stylesheet" href="{% static 'base/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="{% static 'base/css/base.css' %}">

    <script src="{% static "base/js/bootstrap.min.js" %}"></script>
    <script src="{% static "base/js/jquery-3.7.1.min.js" %}"></script>
    <script src="{% static "base/js/base.js" %}"></script>

    {% block head %}{% endblock head %}
</head>
<body>
    <div class="toast-container top-0 end-0 p-3">
        <!-- Then put toasts within -->
        {% for message in messages %}
        <div class="toast" role="alert" aria-live="assertive" aria-atomic="true">
          <div class="toast-header">
            <strong class="me-auto">Bootstrap</strong>
            <small class="text-body-secondary">just now</small>
            <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
          </div>
          <div class="toast-body">
            {{ message }}
          </div>
        </div>
        {% endfor %}
    </div>

    <div class="container-fluid">
        <div class="row">
            <nav class="col-md-3 col-lg-2 d-none d-md-flex flex-column bg-light sidebar flex-shrink-0">
                <div class="d-flex justify-content-center align-items-center">
                    <img src="{% static 'base/img/logo.png' %}" alt="Logo do site" height="70">
                    <h1 class="fs-2 px-2">IStock</h1>
                </div>
                <hr>
                <ul class="nav nav-pills flex-column flex-grow-1">
                    <li>
                        <a href="{% url 'suppliers:index' %}" class="nav-link link-dark">
                            <i class="bi bi-box-seam"></i>
                            Fornecedores
                        </a>
                    </li>
                    <li>
                        <a href="{% url "products:index" %}"class="nav-link link-dark">
                            <i class="bi bi-grid"></i>
                            Produtos
                        </a>
                    </li>
                    <li>
                        <a href="{% url "products:index_category" %}"class="nav-link link-dark">
                            <i class="bi bi-bookmark"></i>
                            Categorias
                        </a>
                    </li>
                    <li>
                        <a href="{% url "users:index" %}"class="nav-link link-dark">
                            <i class="bi bi-people"></i>
                            Usuários
                        </a>
                    </li>
                </ul>
                <hr>
                <ul class="nav nav-pills">
                    <li>
                        <form action={% url 'users:logout' %} method="POST">
                            {% csrf_token %}
                            <button type="submit" class="nav-link link-dark">
                                <i class="bi bi-box-arrow-left"></i>
                                Sair
                            </button>
                        </form>
                    </li>
                </ul>
            </nav>

            <main class="col-md-9 col-lg-10 ml-sm-auto p-md-4 overflow-auto">
                <div class="container mt-4">
                    {% block content %}{% endblock %}
                </div>
            </main>
        </div>
    </div>
</body>
</html>